dataset: visa
data_root: ./datasets/visa
visa_split_csv: ./datasets/visa/split_csv/1cls.csv

model_name: dinov3_vitb16
backbone_ckpt: ./weights/dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth
device: cuda:0
resolution: 512
backbone_last_n_layers: 8
backbone_layer_agg: avg

shots_list: [1, 2, 4, 8]
seed: 0

epochs: 2000
lr: 3.0e-4
mask_ratio: 0.2
a: 2.0

gnn_layers: 3
latent_dim: 256
gnn_hidden_dims: [256, 256, 256]
dropout: 0.3

topk_ratio: 0.01
